### PR TITLE
Compile all files always

### PR DESCRIPTION
**Pull request by thejpster**

### CODE REVIEW

**Review by 9names — APPROVED** [review]
Looks good to me

**Comment by thejpster** [comment]
How do we feel about not picking a chip by default, thus this being a breaking change?

**Comment by 9names** [comment]
> How do we feel about not picking a chip by default, thus this being a breaking change?

Conflicted. I hate breaking existing workflows.
My assumption is that we have few users outside of the current contributors, but we have little visibility on it so it's hard to gauge how correct that is.

If we switch to not picking one by default now, we break every existing user but save ourselves having to make changes twice downstream. There is no valid feature/choice from before and after this PR that we can move any existing code to in advance, so we would have to pin downstream crates to a previous git commit and undo that when changing bootloader if we wanted to avoid breakage.
Or just accept that there will be temporary breakage and hope that no-one is impacted.

If we stick with the current impl, this will be a breaking change for run-from-ram users and a mild inconvenience to people wanting to have AT25SF128A as the default bootloader. That should be a small subset of our users, and I expect those users are experienced enough to quickly deal with this sort of break. We can update the HAL and any example crates to use a specific BOOT2 some time later to avoid the default feature change being an issue.

**Comment by thejpster** [comment]
So, did we agree in #6 to take out the features and let the BSP pick the right bootloader?

**Comment by 9names** [comment]
I think we did, yes.
We can always add this functionality (or something equivalent) later if we have a need for it.

**Comment by thejpster** [comment]
Features are gone!

**Review by 9names — APPROVED** [review]

**Pull request merged**
