### PR TITLE
Add AT25SF128A flash support

### PR DESCRIPTION
**Pull request by taunusflieger**
Hi,

I ddded support for AT25SF128A flash (used by Adrduino Nano RP2040 Connect) - pulled from up-stream PICO SDK. See :https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/boot_stage2/boot2_at25sf128a.S

Please let me know what you think

Best
Michael

### CODE REVIEW

**Comment by thejpster** [comment]
This looks great - thank you for the PR!

Thinking about how this gets used, I think I'd prefer it if we always build all three bootloaders, and export them as three separate variables. We could use features to export one of the three as "DEFAULT_BOOT2" or something.

This also means we check all the source (and asm) files with one `cargo build` rather than having to remember to build repeatedly with each and every feature flag everytime we want to run a check build.

I think the Winbond support should go behind a feature flag too, but maybe I can be the default to avoid breaking existing code.

**Comment by taunusflieger** [comment]
I think your proposal would be a next step providing a different way to build the boot2 binaries and maybe provide them as independent releases at Github - I hope I did understand your comment right.

**Comment by thejpster** [comment]
I think it applies to this PR. Currently this PR forces people to choose a flash chip at compile time (ok) but only compiles the code for that chip (not OK). I'd like to see a change this PR changed to always build all the variants, and then features used to control which one is exported as the 'default'.

**Comment by taunusflieger** [comment]
With the feature approach I just followed what has already been defined in build.rs - prior to my PR one had already to choose between build for flash or RAM execution by setting the appropriate feature. It was not building both variants at the same time. If you want to change that - no problem - just wanted to double check

**Comment by thejpster** [comment]
Yes, that's right - there's a compilation gating feature in there already and I think we should fix this before we add too many more variants. But that's just my view - the @rp-rs/rp-rs should feel free to chip in.

**Comment by 9names** [comment]
My preference is to build all the variants every time.
It would make binary releases slightly easier and ensure everything works, but the main benefit is that there is [slightly] less magic for people new to Rust. And people browsing the code who open main.rs first before checking Cargo.toml

However, I don't expect that in this pull request - it already does all that it needs to.
I'd like to merge this code first, and have a new PR to build all variants.

**Comment by thejpster** [comment]
OK, I'm OK with that - can someone open an issue to remind us?

**Review by 9names — APPROVED** [review]
Code looks good, future direction is set in #6. Let's get this merged!

**Pull request merged**
